component_depth: 1
languages:
- javascript

exclude:
- /MusicHub/public/soundmanager/script/soundmanager2-nodebug-jsmin\.js
- /MusicHub/public/soundmanager/script/soundmanager2-nodebug\.js
- /MusicHub/public/soundmanager/script/soundmanager2-jsmin\.js
- /MusicHub/public/soundmanager/script/soundmanager2\.js
- /MusicHub/public/soundmanager/demo/bar-ui/script/demo\.js
- /MusicHub/public/soundmanager/demo/bar-ui/script/bar-ui\.js
