component_depth: 3
languages:
- javascript

exclude:
- /MusicHub/api_view/public/soundmanager/script/soundmanager2-nodebug-jsmin\.js
- /MusicHub/api_view/public/soundmanager/script/soundmanager2-nodebug\.js
- /MusicHub/api_view/public/soundmanager/script/soundmanager2-jsmin\.js
- /MusicHub/api_view/public/soundmanager/script/soundmanager2\.js
- /MusicHub/api_view/public/soundmanager/demo/bar-ui/script/demo\.js
- /MusicHub/api_view/public/soundmanager/demo/bar-ui/script/bar-ui\.js
- /MusicHub/seed/seed\.js
- /MusicHub/Gruntfile\.js
